Replace InstanceSuffix with MonitorId
signalfx/collectd pull request #21
Opened 2018-07-13 14:38 UTC by asuresh4

Updating the way we add monitorID to GenericJMX plugins. We use InstanceSuffix in the Connection block to add this dimension to plugin instance, updating the config name to MonitorId. 

Also, this update is being made in a manner that we can extend this set up to collect properties from MBeans as dimensions too.

2018-07-16 12:30 UTC, keitwb approved these changes

2018-07-16 13:42 UTC, asuresh4 commented
Will wait to merge since we have not yet decided whether we will be supporting dimensions from MBeans for standalone collectd. If that's the case, will open a PR against master first for collecting dimensions, rebase neoagent-5.8.0-sfx branch and then make this update.

2018-07-25 17:34 UTC, keitwb requested changes

2018-07-25 17:34 UTC, keitwb commented on bindings/java/org/collectd/java/GenericJMXConfMBean.java
> +      if (i > 0)
Always use brackets around the block of if statements.

2018-07-25 17:34 UTC, keitwb commented on bindings/java/org/collectd/java/GenericJMXConfMBean.java
> +  private String join (String separator, List<String> list) /* {{{ */
This just duplicates the join method in the GenericJMXConfValue class.  Just make it a common util function in a singleton class instead so you don't have the duplication.

2018-07-27 20:23 UTC, keitwb approved these changes

2018-07-30 18:41 UTC, merged